### ISSUE TITLE
Separable NMF algorithm

### ISSUE THREAD

**Issue by ahwillia** [JuliaStats/NMF.jl#11]
I made a quick package here that implements [Arora et al.'s polynomial time algorithm](http://arxiv.org/abs/1212.4777) for NMF on separable datasets. This could provide a good initialization for the algorithms provided in this package.

https://github.com/ahwillia/SeparableNMF.jl

I'd be happy to work on this further and merge it into `NMF.jl` if there is interest.

**Comment by lindahua** [comment]
That would be great!

**Comment by ahwillia** [comment]
Ok I'll keep working on this -- is there a good Non-negative least squares solver in julia that I can use?

**Comment by tsano430** [comment]
@ararslan, could I ask what is blocking from reviewing #22 based on #12? I think it is worth merging the Successive Projection Algorithm (SPA) for separable NMF into `NMF.jl`. Thanks.
