### ISSUE TITLE
Adjust interface to allow specification of W and H

### ISSUE THREAD

**Issue by jsams** [JuliaStats/NMF.jl#19]
If I run the nnmf function and it fails to converge, I should be able to rerun it with the current state of W and H rather than having to start from scratch. The current function interface does not allow this.

expected to be able to do this:

```
smallX = sprand(100, 400, 0.3)
nnmfX = nnmf(smallX, 5, init=:random)
while !nnmfX.converged
    nnmfX = nnmf(smallX, 5, W=nnmfX.W, H=nnmfX.H)
end
```

**Comment by lnacquaroli** [comment]
This would be great to have, something like the `'replicates'` in [Matlab](https://www.mathworks.com/help/stats/nnmf.html), chosing the best option to be returned.

**Comment by jsams** [comment]
I obviously don't need this anymore. But at the time, what I was trying to do was inject the W and H matrices that I had stored and then to inject them into the algorithm. Having replicates doesn't solve that use case. Feel free to keep closed if you don't care.

**Comment by tsano430** [comment]
@jsams I'm very sorry for closing this issue. I misunderstood it. Maybe, `:custom` in #49 is the feature you intended. I don't know if it is the correct answer, but I hope it helps you.

```julia
smallX = sprand(100, 400, 0.3)
nnmfX = nnmf(smallX, 5, init=:random)
while !nnmfX.converged
    nnmfX = nnmf(smallX, 5, init=:custom, W0=nnmfX.W, H0=nnmfX.H)
end
```

**Comment by jsams** [comment]
Looks like it would! Thanks! And no apologies necessary, I understood why it was closed. My toy example was absolutely solved by the replicates approach. It just so happened that that wasn't what I was actually looking for when I opened this, just a toy example to demonstrate a potential use case. And in any case, I'm not working on NNMF issues these days; so, I don't have any particular needs. Thus why I was content for the issue to remain closed in the devs weren't interested in the feature either.

**Comment by tsano430** [comment]
PR #49 was merged. Ok to close?

**Comment by jsams** [comment]
Yep, thanks!

**Comment by tsano430** [comment]
@ararslan Please close it.

**Comment by tsano430** [comment]
Thank you!
