### ISSUE TITLE
Error with ProjectedALS

### ISSUE THREAD

**Issue by abhijithch** [JuliaStats/NMF.jl#2]
The example for Naive ALS is giving the following error,
`julia> NMF.solve!(NMF.ProjectedALS(maxiter=50),A,W,H)
ERROR: vecnorm not defined
 in evaluate_objv at /home/abhijith/.julia/NMF/src/projals.jl:69
 in nmf_skeleton! at /home/abhijith/.julia/NMF/src/common.jl:84
 in solve! at /home/abhijith/.julia/NMF/src/projals.jl:39`

**Comment by lnacquaroli** [comment]
Hi, the `vecnorm` error still appears as of today in the ProjectedALS.
