### ISSUE TITLE
ETA for Julia 0.7-1.0 compatible release?

### ISSUE THREAD

**Issue by charlesll** [JuliaStats/NMF.jl#27]
Hi,

Do you have any ETA for the Julia 1.0 compatible tag / release?

Thanks,
Charles.

**Comment by haberdashPI** [comment]
As a stop gap, I have been using the #24 with success on 0.7. For my data it gives equivalent results to the 0.6 code.

**Comment by ararslan** [comment]
NMF has been tagged so you should be good now.
