### ISSUE TITLE
different scaling factor in nndsvd comparing to original paper

### ISSUE THREAD

**Issue by ccshao** [JuliaStats/NMF.jl#32]
The implementation of nndsvd in NMF.jl uses a different scaling factor. In the initialization.jl file, the u and v (in the case of mp >= mn) are 
```
scalepos!(view(W,:,j), x, 1 / xpnrm, vj)
scalepos!(view(Ht,:,j), y, s[j] * mp / ypnrm, vj)
```

while if following the description of the original paper, the u and v would be 
```
ss = sqrt(s[j] * mp)
scalepos!(view(W,:,j), x, ss / xpnrm, vj)
scalepos!(view(Ht,:,j), y, ss / ypnrm, vj)
```
The former implementation leads to a **unit scale of u but "bigger" v** comparing to what is the documented in the original paper, throught both are valid. In the NMF R package, the latter implementation is used.

May I ask what the reasons are behined the modification? Thanks!

**Comment by tsano430** [comment]
It seems that the latter implementation is also used in the scikit-learn.

https://github.com/scikit-learn/scikit-learn/blob/95119c13af77c76e150b753485c662b7c52a41a2/sklearn/decomposition/_nmf.py#L345-L383

**Comment by tsano430** [comment]
Probably I think the modification aims to pass the following test. 

https://github.com/JuliaStats/NMF.jl/blob/e93c0d52563079e282189dd3a24317ef6cc04766/test/initialization.jl#L33

The squared norms of W's columns are not guaranteed to be one in general, so I modified the implementation as in the NMF R package and scikit-learn.
