### ISSUE TITLE
Random initialization with normalization not working properly

### ISSUE THREAD

**Issue by lnacquaroli** [JuliaStats/NMF.jl#34]
```julia

using NMF

X=rand(10,10);

r = nnmf(X, 2, init=:random)
NMF.Result{Float64}([0.0633167 0.14211; 0.0173814 0.195825; … ; 0.139675 0.0609239; 0.0175174 0.174193], [2.13638 1.10415 … 0.504314 1.13698; 1.07696 4.19894 … 4.78298 2.05306], 12, true, 4.892614466421323)

r.W
10×2 Array{Float64,2}:
 0.0633167  0.14211  
 0.0173814  0.195825 
 0.0685418  0.111995 
 0.198279   0.0413312
 0.206879   0.0221328
 0.153456   0.0125537
 0.135189   0.124592 
 0.106836   0.0976132
 0.139675   0.0609239
 0.0175174  0.174193

sum(r.W, dims=1)
1×2 Array{Float64,2}:
 1.09212  1.4119
```
This is odd, since `interf.jl` indicates that normalization is set to `true` when is random:

https://github.com/JuliaStats/NMF.jl/blob/affbab88f0f128ad8ef0e35efc31c63e480b2a2a/src/interf.jl#L18

According to `Readme.md` in `NMF.randinit(X, k[; zeroh=false, normalize=false])`, if `normalize=true` then they should sum up to 1. But `import NMF` does not work [https://github.com/JuliaStats/NMF.jl/issues/28](https://github.com/JuliaStats/NMF.jl/issues/28).

**Comment by tsano430** [comment]
If `normalize=true` then the initial value of W generated by `randinit` is guaranteed to be normalized. 

```julia
using NMF
X=rand(10,10);
r = nnmf(X, 2, init=:random, maxiter=0);
sum(r.W, dims=1)
1×2 Array{Float64,2}:
 1.0  1.0
```

However, there is no guarantee that the W obtained from each iterative algorithm will be normalized. 

```julia
using NMF
X=rand(10,10);
r = nnmf(X, 2, init=:random, maxiter=100);
sum(r.W, dims=1)
1×2 Array{Float64,2}:
 1.30126  1.43164
```
