### ISSUE TITLE
Export more functions / increase flexibility

### ISSUE THREAD

**Issue by ahwillia** [JuliaStats/NMF.jl#8]
I couldn't reproduce [these examples](https://github.com/JuliaStats/NMF.jl#use-naive-als) at the bottom of the `README` file.

I had to update `NMF.jl` to export more functions:

```julia
export nnmf,randinit,nndsvd,ProjectedALS,ALSPGrad,MultUpdate
```

The `nnmf` interface is nice but was not flexible enough for me. I wanted to be able to store intermediate solutions along the optimization path. To be specific, this is my code (it works now after exporting the above functions):

```julia
# initialize
W, H = NMF.nndsvd(faces, k; variant=:ar)

# store W and H at several of fitting
m,n = size(faces)
W_hist = Array(Float64,m,k,n_epochs)
H_hist = Array(Float64,k,n,n_epochs)

# optimize (e.g. 100 total iterations in epochs of 10)
n_epochs = 10
iters_per_epoch = 10
for i = 1:n_epochs
  NMF.solve!(NMF.ALSPGrad{Float64}(maxiter=iters_per_epoch), faces, W, H)
  W_hist[:,:,i] = W # store intermediate result
  H_hist[:,:,i] = H
end
```

Thus, I propose either modifying the module to export the above functions, or alter the `nnmf` interface function to start from a user-specified `W` and `H` to cover the above use-case.

**Comment by lindahua** [comment]
If a function is not exported, one can still call it using ``NMF.xxx``.

**Comment by ahwillia** [comment]
Yes apologies -- I wasn't aware of this at first
